config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'pages#admin'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/privacy'

  resources :appointments
  resources :doctor_profiles
  resources :patient_profiles
  devise_for :users

  root 'home#index'

end

app/models/doctor_profile.rb
class DoctorProfile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :photo, DoctorPhotoUploader

  def doctor_identity
  	[title, first_name, last_name, post_nominals].compact.join(' ')
  end

  extend FriendlyId
  friendly_id :doctor_identity, use: :slugged

  acts_as_taggable
  
end

app/controllers/doctor_profiles_controller.rb
class DoctorProfilesController < ApplicationController
  before_action :set_doctor_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]
  # GET /doctor_profiles
  # GET /doctor_profiles.json
  def index
    if params[:tag]
      @doctor_profiles = DoctorProfile.tagged_with(params[:tag])
    else
      @doctor_profiles = DoctorProfile.all
    end
    @tags = DoctorProfile.tag_counts_on(:tags)
  end

  # GET /doctor_profiles/1
  # GET /doctor_profiles/1.json
  def show
  end

  # GET /doctor_profiles/new
  def new
    @doctor_profile = DoctorProfile.new
  end

  # GET /doctor_profiles/1/edit
  def edit
  end

  # POST /doctor_profiles
  # POST /doctor_profiles.json
  def create
    @doctor_profile = DoctorProfile.new(doctor_profile_params)
    @doctor_profile.user = current_user
    respond_to do |format|
      if @doctor_profile.save
        format.html { redirect_to @doctor_profile, notice: 'Doctor profile was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_profile }
      else
        format.html { render :new }
        format.json { render json: @doctor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_profiles/1
  # PATCH/PUT /doctor_profiles/1.json
  def update
    respond_to do |format|
      if @doctor_profile.update(doctor_profile_params)
        format.html { redirect_to @doctor_profile, notice: 'Doctor profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_profile }
      else
        format.html { render :edit }
        format.json { render json: @doctor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_profiles/1
  # DELETE /doctor_profiles/1.json
  def destroy
    @doctor_profile.destroy
    respond_to do |format|
      format.html { redirect_to doctor_profiles_url, notice: 'Doctor profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_profile
      @doctor_profile = DoctorProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_profile_params
      params.require(:doctor_profile).permit(:title, :first_name, :last_name, :photo, :bio, :post_nominals, :user_id, :tag_list)
    end
end

app/helpers/doctor_profiles_helper.rb
module DoctorProfilesHelper
end

app/views/doctor_profiles/_form.html.erb
<%= simple_form_for(@doctor_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :photo %>
    <%= f.input :bio %>
    <%= f.input :post_nominals %>
    <%= f.input :tag_list, label: 'Specialisations', placeholder: 'eg. Pediatrics, dermatolgist' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctor_profiles/edit.html.erb
<h1>Editing Doctor Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor_profile %> |
<%= link_to 'Back', doctor_profiles_path %>

app/views/doctor_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctor Profiles <% if params[:tag] %>- <%= params[:tag] %><% end %></h1>
<% @tags.each do |tag| %>
	<%= link_to tag.name, doctor_profiles_path(tag: tag.name), class: 'btn btn-info btn-sm' %>
<% end %>
<%= link_to 'All Doctors', doctor_profiles_path, class: 'btn btn-warning btn-sm' %>


<table class="table table-hover">
 <tbody>
    <% @doctor_profiles.each do |doctor_profile| %>
      <tr>
        <td><%= image_tag doctor_profile.photo, width: '80px', class: 'img-responsive' %></td>
        <td><%= link_to doctor_profile.doctor_identity, doctor_profile %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/doctor_profiles/new.html.erb
<h1>New Doctor Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', doctor_profiles_path %>

app/views/doctor_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= image_tag @doctor_profile.photo, class: 'img-responsive img-thumbnail img-circle' %>
        <p>
          <%= @doctor_profile.title %> 
          <%= @doctor_profile.first_name %>
          <%= @doctor_profile.last_name %> 
          <%= @doctor_profile.post_nominals %>
        </p>
        <p>
          <strong>Bio:</strong>
          <br>
          <%= @doctor_profile.bio %>
        </p>

        <p><strong>Specialties</strong></p>
        <ul>
          <% @doctor_profile.tags.each do |tag| %>
            <li><%= link_to tag, doctor_profiles_path(tag: tag.name) %></li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
          
            <%= link_to 'Edit', edit_doctor_profile_path(@doctor_profile), class: 'btn btn-warning btn-sm' %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>